### ISSUE TITLE
Run with machinekit

### ISSUE THREAD

**Issue by summerlotus513** [zultron/linuxcnc-ethercat#2]
I am using an older version of machinekit https://github.com/machinekit/machinekit
I want to use this library to realize the functions of ethercat, but when I compile, I find that it only supports the linuxcnc environment, so what should I do?

**Comment by zultron** [comment]
I'm sure you know the repo you link to is no longer maintained, and I'm sure you know official advice is to migrate to the `machinekit-hal` and `EMCApplication` repos!

If you absolutely must use that outdated code, you might have to search back in git history to find an older revision in this repo that will work.  I can't think of any changes that would break support for the legacy `machinekit` repo, but of course changes over at least the last year haven't been tested, and bitrot sets in fast.

If you want to post build logs showing the problem, you can reopen this issue, and I'll see if anything obvious stands out.  For now, I'm closing this issue.  Good luck!
